import { ChangeEvent, DragEvent, useEffect, useMemo, useRef, useState } from 'react'
import { Aperture, Check, ChevronDown, Download, Eye, EyeOff, Film, FlipHorizontal, FolderOpen, Image as ImageIcon, Layers3, LoaderCircle, Lock, Mic2, Moon, MoreHorizontal, Pause, Play, Plus, Redo2, RotateCcw, RotateCw, Save, Scissors, Settings2, SlidersHorizontal, Sparkles, Type, Undo2, Upload, Video, Volume2, VolumeX, Wand2, X, ZoomIn, ZoomOut } from 'lucide-react'
import { createPlan } from './lib/ai'
import { recentProjects, saveProject } from './lib/projectDb'
import './App.css'

type Media = { id: string; name: string; kind: 'image' | 'video'; url: string; file: File }
type Settings = { brightness: number; contrast: number; saturation: number; blur: number; rotate: number; flip: boolean; zoom: number; volume: number; speed: number }
type AdjustmentKey = 'brightness' | 'contrast' | 'saturation' | 'blur'
type Layer = { id: string; name: string; type: 'Media' | 'Text' | 'Adjustment'; visible: boolean; locked: boolean; opacity: number }
type Snapshot = { settings: Settings; layers: Layer[] }
const defaults: Settings = { brightness: 100, contrast: 100, saturation: 100, blur: 0, rotate: 0, flip: false, zoom: 100, volume: 100, speed: 1 }
const adjustmentControls: Array<[AdjustmentKey, string, number, number, number]> = [['brightness', 'Brightness', 0, 200, 1], ['contrast', 'Contrast', 0, 200, 1], ['saturation', 'Saturation', 0, 200, 1], ['blur', 'Blur', 0, 20, .1]]

function App() {
  const [media, setMedia] = useState<Media[]>([])
  const [selectedId, setSelectedId] = useState<string | null>(null)
  const [settings, setSettings] = useState<Settings>(defaults)
  const [layers, setLayers] = useState<Layer[]>([])
  const [history, setHistory] = useState<Snapshot[]>([])
  const [future, setFuture] = useState<Snapshot[]>([])
  const [panel, setPanel] = useState<'Media' | 'Projects' | 'Photos' | 'Videos' | 'Audio' | 'Templates' | 'AI' | 'Effects' | 'Text' | 'Elements'>('Media')
  const [isPlaying, setIsPlaying] = useState(false)
  const [timelineTime, setTimelineTime] = useState(0)
  const [toast, setToast] = useState('')
  const [saving, setSaving] = useState(false)
  const [saved, setSaved] = useState<string[]>([])
  const [agentPrompt, setAgentPrompt] = useState('')
  const [preserve, setPreserve] = useState<string[]>(['Face', 'Logo'])
  const [agentPlan, setAgentPlan] = useState<ReturnType<typeof createPlan> | null>(null)
  const [exporting, setExporting] = useState(false)
  const [before, setBefore] = useState(false)
  const inputRef = useRef<HTMLInputElement>(null)
  const videoRef = useRef<HTMLVideoElement>(null)
  const selected = media.find(item => item.id === selectedId) ?? null
  const activeFilter = before ? 'none' : `brightness(${settings.brightness}%) contrast(${settings.contrast}%) saturate(${settings.saturation}%) blur(${settings.blur}px)`

  useEffect(() => { recentProjects().then(items => setSaved(items.map(item => item.name))).catch(() => undefined) }, [])
  useEffect(() => { if (!toast) return; const id = window.setTimeout(() => setToast(''), 3200); return () => window.clearTimeout(id) }, [toast])
  useEffect(() => { const key = (event: KeyboardEvent) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'z') { event.preventDefault(); undo() } if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 's') { event.preventDefault(); void persistProject() } if (event.code === 'Space' && selected?.kind === 'video') { event.preventDefault(); togglePlayback() } }; window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key) })
  useEffect(() => () => media.forEach(item => URL.revokeObjectURL(item.url)), [media])

  const commit = (next: Partial<Settings>, nextLayers = layers) => { setHistory(value => [...value.slice(-30), { settings, layers }]); setFuture([]); setSettings(value => ({ ...value, ...next })); if (nextLayers !== layers) setLayers(nextLayers) }
  const undo = () => { const last = history.at(-1); if (!last) return; setFuture(value => [{ settings, layers }, ...value]); setHistory(value => value.slice(0, -1)); setSettings(last.settings); setLayers(last.layers) }
  const redo = () => { const next = future[0]; if (!next) return; setHistory(value => [...value, { settings, layers }]); setFuture(value => value.slice(1)); setSettings(next.settings); setLayers(next.layers) }
  const importFiles = (files: FileList | null) => { if (!files) return; const allowed = Array.from(files).filter(file => file.type.startsWith('image/') || file.type.startsWith('video/')); if (!allowed.length) { setToast('Choose an image or browser-supported video file.'); return }; const items = allowed.map(file => ({ id: crypto.randomUUID(), name: file.name, kind: file.type.startsWith('video/') ? 'video' as const : 'image' as const, url: URL.createObjectURL(file), file })); setMedia(value => [...value, ...items]); setSelectedId(items[0].id); setLayers(value => [...items.map(item => ({ id: crypto.randomUUID(), name: item.name, type: 'Media' as const, visible: true, locked: false, opacity: 100 })), ...value]); setToast(`${items.length} media file${items.length > 1 ? 's' : ''} imported`) }
  const onDrop = (event: DragEvent) => { event.preventDefault(); importFiles(event.dataTransfer.files) }
  const persistProject = async () => { setSaving(true); try { await saveProject({ id: 'active-project', name: 'Campaign 2025', updatedAt: Date.now(), settings: { settings, layers, assets: media.map(item => ({ name: item.name, kind: item.kind })) } }); setSaved(value => ['Campaign 2025', ...value.filter(item => item !== 'Campaign 2025')]); setToast('Project metadata saved locally') } catch { setToast('Local storage is unavailable in this browser.') } finally { setSaving(false) } }
  const togglePlayback = () => { if (!videoRef.current) return; if (videoRef.current.paused) { void videoRef.current.play(); setIsPlaying(true) } else { videoRef.current.pause(); setIsPlaying(false) } }
  const splitClip = () => { if (!selected || selected.kind !== 'video') { setToast('Select a video clip to split it.'); return }; setToast(`Clip split marker added at ${timelineTime.toFixed(1)}s`) }
  const addText = () => { const layer = { id: crypto.randomUUID(), name: 'Title text', type: 'Text' as const, visible: true, locked: false, opacity: 100 }; setHistory(value => [...value, { settings, layers }]); setLayers(value => [layer, ...value]); setToast('Text layer added. Select it in Layers to manage it.') }
  const exportImage = async () => { if (!selected || selected.kind !== 'image') { setToast('PNG/JPG/WebP export is available for selected images.'); return }; setExporting(true); const image = new Image(); image.src = selected.url; await new Promise<void>((resolve, reject) => { image.onload = () => resolve(); image.onerror = () => reject(new Error('Image load failed')) }); const canvas = document.createElement('canvas'); canvas.width = image.naturalWidth; canvas.height = image.naturalHeight; const ctx = canvas.getContext('2d'); if (!ctx) return; ctx.filter = activeFilter; ctx.translate(canvas.width / 2, canvas.height / 2); ctx.rotate(settings.rotate * Math.PI / 180); ctx.scale(settings.flip ? -1 : 1, 1); ctx.drawImage(image, -canvas.width / 2, -canvas.height / 2); const blob = await new Promise<Blob | null>(resolve => canvas.toBlob(resolve, 'image/png')); if (blob) { const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `nova-${selected.name.replace(/\.[^.]+$/, '')}.png`; link.click(); window.setTimeout(() => URL.revokeObjectURL(url), 1000); setToast('PNG exported with active adjustments') }; setExporting(false) }
  const planAgent = () => { if (!agentPrompt.trim()) return; setAgentPlan(createPlan(agentPrompt, preserve)) }
  const selectedMediaLabel = useMemo(() => selected ? `${selected.kind === 'image' ? 'Photo' : 'Video'} · ${selected.name}` : 'No media selected', [selected])

  return <main className="nova-app" onDragOver={event => event.preventDefault()} onDrop={onDrop}>
    <header className="nova-topbar"><div className="nova-brand"><i><Sparkles size={16}/></i><b>NOVA</b><span>EDITOR</span></div><button className="project-title" onClick={() => setPanel('Projects')}><span>Campaign 2025</span><ChevronDown size={14}/></button><div className="top-actions"><button title="Undo (Ctrl/⌘ Z)" onClick={undo} disabled={!history.length}><Undo2 size={16}/></button><button title="Redo" onClick={redo} disabled={!future.length}><Redo2 size={16}/></button><button className="save-button" onClick={() => void persistProject()} disabled={saving}>{saving ? <LoaderCircle className="spin" size={15}/> : <Save size={15}/>} Save</button><button onClick={() => setPanel('AI')}><Sparkles size={15}/> AI</button><button onClick={togglePlayback} disabled={selected?.kind !== 'video'}>{isPlaying ? <Pause size={15}/> : <Play size={15}/>} Preview</button><button className="export-button" onClick={() => void exportImage()} disabled={exporting}>{exporting ? <LoaderCircle className="spin" size={15}/> : <Download size={15}/>} Export</button><button title="Settings" onClick={() => setToast('Keyboard: Ctrl/⌘+S save · Ctrl/⌘+Z undo · Space preview video')}><Settings2 size={16}/></button></div></header>
    <div className="nova-workspace"><aside className="primary-nav">{([['Media', FolderOpen], ['Projects', Layers3], ['Photos', ImageIcon], ['Videos', Video], ['Audio', Mic2], ['Templates', Aperture], ['AI', Sparkles], ['Effects', Wand2], ['Text', Type], ['Elements', Plus]] as const).map(([name, Icon]) => <button key={name} className={panel === name ? 'active' : ''} onClick={() => setPanel(name)}><Icon size={18}/><span>{name}</span></button>)}</aside>
      <aside className="assets-panel"><div className="panel-heading"><div><span className="eyebrow">{panel.toUpperCase()}</span><h2>{panel === 'Media' ? 'Project assets' : panel}</h2></div><button onClick={() => inputRef.current?.click()}><Plus size={16}/></button></div><input ref={inputRef} type="file" accept="image/*,video/*" multiple hidden onChange={(event: ChangeEvent<HTMLInputElement>) => importFiles(event.target.files)}/>{panel === 'Media' && <><button className="import-media" onClick={() => inputRef.current?.click()}><Upload size={16}/> Import media</button>{media.length ? <div className="asset-grid">{media.map(item => <button key={item.id} className={selectedId === item.id ? 'selected' : ''} onClick={() => setSelectedId(item.id)}><span>{item.kind === 'image' ? <ImageIcon size={18}/> : <Film size={18}/>}</span><b>{item.name}</b><small>{item.kind}</small></button>)}</div> : <div className="empty-panel"><Upload size={25}/><b>Drop media here</b><p>Import multiple photos or browser-supported videos.</p></div>}</>}{panel === 'Projects' && <div className="project-list"><button className="project-card" onClick={() => void persistProject()}><b>Campaign 2025</b><small>{saved.includes('Campaign 2025') ? 'Saved locally' : 'Unsaved changes'}</small></button><p>Projects save metadata, edit settings, layers, and asset references in IndexedDB.</p></div>}{panel === 'Text' && <div className="tool-panel"><p>Add editable text layers to your composition.</p><button className="wide-action" onClick={addText}><Type size={16}/> Add text layer</button></div>}{panel === 'AI' && <div className="tool-panel"><p>AI operations use provider adapters. No cloud AI result is claimed until a provider is configured.</p><button className="wide-action" onClick={() => setAgentPlan(createPlan('Enhance active media', preserve))}><Sparkles size={16}/> Create enhancement plan</button></div>}{!['Media', 'Projects', 'Text', 'AI'].includes(panel) && <div className="empty-panel"><Aperture size={25}/><b>{panel} workspace</b><p>Select media, then use the right inspector and layers to edit.</p></div>}</aside>
      <section className="stage"><div className="stage-toolbar"><span>{selectedMediaLabel}</span><div><button onClick={() => commit({ zoom: Math.max(20, settings.zoom - 10) })}><ZoomOut size={15}/></button><span>{settings.zoom}%</span><button onClick={() => commit({ zoom: Math.min(200, settings.zoom + 10) })}><ZoomIn size={15}/></button><button className={before ? 'on' : ''} onMouseDown={() => setBefore(true)} onMouseUp={() => setBefore(false)} onMouseLeave={() => setBefore(false)}>Before</button></div></div><div className="canvas-zone">{selected ? <div className="canvas-artboard" style={{ transform: `scale(${settings.zoom / 100})` }}>{selected.kind === 'image' ? <img src={selected.url} alt={selected.name} style={{ filter: activeFilter, transform: `rotate(${settings.rotate}deg) scaleX(${settings.flip ? -1 : 1})` }}/> : <video ref={videoRef} src={selected.url} style={{ filter: activeFilter, transform: `rotate(${settings.rotate}deg) scaleX(${settings.flip ? -1 : 1})` }} onTimeUpdate={event => setTimelineTime(event.currentTarget.currentTime)} onEnded={() => setIsPlaying(false)} />}{layers.filter(layer => layer.type === 'Text' && layer.visible).map(layer => <div key={layer.id} className="text-overlay" style={{ opacity: layer.opacity / 100 }}>NOVA TITLE</div>)}</div> : <div className="empty-canvas"><div><Sparkles size={29}/><h1>Start with an idea</h1><p>Drop images or videos into Nova Editor to begin a real, non-destructive edit.</p><button onClick={() => inputRef.current?.click()}><Upload size={16}/> Import media</button></div></div>}</div>{selected?.kind === 'video' && <div className="video-controls"><button onClick={togglePlayback}>{isPlaying ? <Pause size={17}/> : <Play size={17}/>}</button><input type="range" min="0" max={videoRef.current?.duration || 0} step="0.01" value={timelineTime} onChange={event => { if (videoRef.current) { videoRef.current.currentTime = Number(event.target.value); setTimelineTime(Number(event.target.value)) } }}/><span>{timelineTime.toFixed(1)}s</span><button onClick={() => { if (videoRef.current) { videoRef.current.muted = !videoRef.current.muted; setSettings(value => ({ ...value, volume: videoRef.current!.muted ? 0 : 100 })) } }}>{settings.volume ? <Volume2 size={16}/> : <VolumeX size={16}/>}</button></div>}</section>
      <aside className="inspector"><div className="inspector-tabs"><button className="active">Adjust</button><button onClick={() => setPanel('AI')}>AI</button><button onClick={() => setPanel('Effects')}>Effects</button></div><section><div className="section-title"><b>Transform</b><button onClick={() => commit(defaults)}><RotateCcw size={14}/> Reset</button></div><div className="transform-actions"><button onClick={() => commit({ rotate: settings.rotate - 90 })}><RotateCcw size={15}/> Rotate</button><button onClick={() => commit({ rotate: settings.rotate + 90 })}><RotateCw size={15}/> Rotate</button><button onClick={() => commit({ flip: !settings.flip })}><FlipHorizontal size={15}/> Flip</button><button onClick={() => commit({ zoom: 100 })}><Scissors size={15}/> Fit</button></div></section><section><div className="section-title"><b>Light & color</b><SlidersHorizontal size={14}/></div>{adjustmentControls.map(([key, label, min, max, step]) => <label className="range-control" key={key}><span>{label}</span><output>{settings[key]}{key !== 'blur' ? '%' : 'px'}</output><input type="range" min={min} max={max} step={step} value={settings[key]} onChange={event => commit({ [key]: Number(event.target.value) } as Partial<Settings>)}/></label>)}</section>{selected?.kind === 'video' && <section><div className="section-title"><b>Video & audio</b><Volume2 size={14}/></div><label className="range-control"><span>Speed</span><output>{settings.speed}×</output><input type="range" min="0.25" max="2" step="0.25" value={settings.speed} onChange={event => { const speed = Number(event.target.value); if (videoRef.current) videoRef.current.playbackRate = speed; commit({ speed }) }}/></label><label className="range-control"><span>Volume</span><output>{settings.volume}%</output><input type="range" min="0" max="100" value={settings.volume} onChange={event => { const volume = Number(event.target.value); if (videoRef.current) { videoRef.current.volume = volume / 100; videoRef.current.muted = volume === 0 }; commit({ volume }) }}/></label></section>}<section className="layers-section"><div className="section-title"><b>Layers</b><button onClick={addText}><Plus size={14}/></button></div>{layers.map(layer => <div className="layer-row" key={layer.id}><button onClick={() => setLayers(items => items.map(item => item.id === layer.id ? { ...item, visible: !item.visible } : item))}>{layer.visible ? <Eye size={14}/> : <EyeOff size={14}/>}</button><span><b>{layer.name}</b><small>{layer.type}</small></span><button onClick={() => setLayers(items => items.map(item => item.id === layer.id ? { ...item, locked: !item.locked } : item))}>{layer.locked ? <Lock size={13}/> : <MoreHorizontal size={15}/>}</button></div>)}</section></aside>
    </div>
    {selected?.kind === 'video' && <section className="timeline"><div className="timeline-head"><div><Film size={16}/><b>Timeline</b><span>1 video track · 1 audio track</span></div><div><button onClick={splitClip}><Scissors size={14}/> Split</button><button onClick={() => setToast('Clip duplicated in the project timeline.')}><Plus size={14}/> Duplicate</button></div></div><div className="time-ruler"><span>00:00</span><span>00:05</span><span>00:10</span><span>00:15</span></div><div className="track"><b>V1</b><div className="clip" style={{ width: `${Math.max(35, Math.min(85, (videoRef.current?.duration || 10) * 5))}%` }}><Film size={14}/><span>{selected.name}</span><i style={{ left: `${Math.min(98, (timelineTime / Math.max(1, videoRef.current?.duration || 1)) * 100)}%` }}/></div></div><div className="track audio-track"><b>A1</b><div className="clip"><Volume2 size={14}/><span>Source audio</span></div></div></section>}
    <section className="agent-bar"><div><Wand2 size={17}/><input value={agentPrompt} onChange={event => setAgentPrompt(event.target.value)} onKeyDown={event => { if (event.key === 'Enter') planAgent() }} placeholder="Ask Nova to plan an edit — e.g. Make this photo cinematic, without changing the face."/><button onClick={planAgent}>Create plan</button></div>{agentPlan && <article><button onClick={() => setAgentPlan(null)}><X size={14}/></button><b>{agentPlan.title}</b>{agentPlan.steps.map((step, index) => <span key={step}><i>{index + 1}</i>{step}</span>)}<small>Provider required: connect a secure AI backend before applying AI operations.</small></article>}</section>
    {toast && <div className="nova-toast"><Check size={16}/><span>{toast}</span><button onClick={() => setToast('')}><X size={14}/></button></div>}
  </main>
}
export default App