import { useEffect, useRef, useState } from 'react'
import { Aperture, ChevronDown, Check, Clapperboard, Cloud, Download, Film, FolderOpen, Grid2X2, Image as ImageIcon, Layers3, Library, MonitorPlay, MousePointer2, Pause, Play, Plus, RotateCcw, Search, Settings2, SlidersHorizontal, Sparkles, Type, Upload, Video, Wand2, X, ZoomIn, ZoomOut, ScanFace, Captions, Eraser, Palette, Volume2, Crop, ScanLine, SlidersHorizontal as Tune, Smartphone, Zap, PenTool, Shapes, Frame, LayoutTemplate, FileText, FolderHeart, AudioLines, BadgeCheck } from 'lucide-react'
import './App.css'

type Asset = { name: string; type: 'image' | 'video'; url: string }
type Toast = { title: string; text: string } | null
const tools = [{ icon: MousePointer2, label: 'Select' }, { icon: Layers3, label: 'Layers' }, { icon: Type, label: 'Text' }, { icon: Shapes, label: 'Shapes' }, { icon: PenTool, label: 'Pen' }, { icon: Crop, label: 'Crop' }, { icon: Wand2, label: 'AI tools' }, { icon: Aperture, label: 'Retouch' }, { icon: Grid2X2, label: 'Layout' }]
const filterOptions = ['Original', 'Cinematic', 'Portrait', 'Noir', 'Velvet']
const aiTools = [{ icon: Wand2, name: 'Auto edit', copy: 'Balance color, light & framing' }, { icon: Eraser, name: 'Remove background', copy: 'Precise subject isolation' }, { icon: ScanFace, name: 'Portrait refine', copy: 'Natural skin & expression' }, { icon: Captions, name: 'Auto captions', copy: 'Transcribe & style speech' }, { icon: Palette, name: 'Color match', copy: 'Apply a reference grade' }, { icon: Volume2, name: 'Voice clean-up', copy: 'Remove noise & echoes' }]
const suiteTools = [{ icon: LayoutTemplate, title: 'Express layouts', copy: 'Instant social, web, and presentation formats' }, { icon: PenTool, title: 'Vector drawing', copy: 'Precision paths and shape construction' }, { icon: Aperture, title: 'Photo finishing', copy: 'Non-destructive image correction workflow' }, { icon: Film, title: 'Video timeline', copy: 'Scenes, transitions, audio, and captions' }, { icon: AudioLines, title: 'Audio mix', copy: 'Voice enhancement and sound cleanup' }, { icon: FileText, title: 'Brand kits', copy: 'Reusable colors, type, logos and exports' }]

function App() {
  const [mode, setMode] = useState<'Photo' | 'Video'>('Photo')
  const [activeTool, setActiveTool] = useState('Select')
  const [asset, setAsset] = useState<Asset | null>(null)
  const [filter, setFilter] = useState('Original')
  const [zoom, setZoom] = useState(84)
  const [playing, setPlaying] = useState(false)
  const [showExport, setShowExport] = useState(false)
  const [showAi, setShowAi] = useState(false)
  const [showInstall, setShowInstall] = useState(false)
  const [fireflyMode, setFireflyMode] = useState(false)
  const [hub, setHub] = useState<'projects' | 'library' | null>(null)
  const [autoEditing, setAutoEditing] = useState(false)
  const [exporting, setExporting] = useState(false)
  const [exportFormat, setExportFormat] = useState('MP4 · 4K · H.264')
  const [exportQuality, setExportQuality] = useState('High · 90%')
  const [toast, setToast] = useState<Toast>(null)
  const mobileInstallUrl = `${window.location.origin}/nova-studio-mobile-install.html`
  const [adjustments, setAdjustments] = useState({ exposure: 54, contrast: 58, saturation: 54 })
  const inputRef = useRef<HTMLInputElement>(null)
  const videoRef = useRef<HTMLVideoElement>(null)
  const upload = (files: FileList | null) => { const file = files?.[0]; if (!file) return; const type = file.type.startsWith('video') ? 'video' : 'image'; setAsset({ name: file.name, type, url: URL.createObjectURL(file) }); setMode(type === 'video' ? 'Video' : 'Photo'); setToast({ title: 'Media imported', text: `${file.name} is ready to edit.` }) }
  const notify = (title: string, text: string) => setToast({ title, text })
  const runAutoEdit = () => { setShowAi(false); setAutoEditing(true); window.setTimeout(() => { setAutoEditing(false); setFilter('Cinematic'); setAdjustments({ exposure: 57, contrast: 64, saturation: 61 }); notify('Edit applied', 'AI balanced color, contrast, composition, and detail.') }, 1900) }
  const action = (name: string) => {
    setShowAi(false)
    if (!asset) { notify('Import media first', 'Choose a photo or video before applying this professional tool.'); return }
    if (name.includes('Background')) setFilter('Portrait')
    if (name.includes('retouch') || name.includes('Portrait')) setAdjustments({ ...adjustments, exposure: 59, saturation: 55 })
    if (name.includes('Color')) setFilter('Cinematic')
    if (name.includes('crop') || name.includes('reframe')) setZoom(100)
    notify(`${name} applied`, 'The active canvas has been updated. Export when you are ready.')
  }
  const enableFirefly = () => { setFireflyMode(true); setShowAi(false); notify('Firefly workflow enabled', 'Generative-workflow controls are enabled. An Adobe account and API credentials are required for Adobe cloud generation.') }
  const triggerDownload = (href: string, filename: string) => { const link = document.createElement('a'); link.href = href; link.download = filename; document.body.appendChild(link); link.click(); link.remove() }
  const exportProject = async () => {
    setExporting(true)
    const projectData = { app: 'Nova Studio', project: 'Untitled project', format: exportFormat, sourceMedia: asset?.name ?? null, filter, adjustments, exportedAt: new Date().toISOString() }
    if (asset?.type === 'image' && /PNG|JPG|WebP/.test(exportFormat)) {
      const image = new Image(); image.src = asset.url
      await new Promise<void>((resolve, reject) => { image.onload = () => resolve(); image.onerror = () => reject(new Error('Image could not be rendered')) })
      const max = exportFormat.includes('4K') ? 3840 : exportFormat.includes('High') ? 2400 : 1600
      const scale = Math.min(1, max / Math.max(image.naturalWidth, image.naturalHeight)); const canvas = document.createElement('canvas')
      canvas.width = Math.max(1, Math.round(image.naturalWidth * scale)); canvas.height = Math.max(1, Math.round(image.naturalHeight * scale))
      const ctx = canvas.getContext('2d')!; ctx.filter = filter === 'Noir' ? 'grayscale(1) contrast(1.15)' : filter === 'Cinematic' ? 'contrast(1.12) saturate(1.18)' : filter === 'Portrait' ? 'brightness(1.06) saturate(1.05)' : filter === 'Velvet' ? 'contrast(1.05) saturate(.9)' : 'none'; ctx.drawImage(image, 0, 0, canvas.width, canvas.height)
      const type = exportFormat.includes('PNG') ? 'image/png' : exportFormat.includes('WebP') ? 'image/webp' : 'image/jpeg'; const quality = exportQuality.includes('Maximum') ? .98 : exportQuality.includes('High') ? .9 : .75
      const blob = await new Promise<Blob | null>(resolve => canvas.toBlob(resolve, type, quality)); if (blob) { const url = URL.createObjectURL(blob); triggerDownload(url, `nova-edited-${asset.name.replace(/\.[^.]+$/, '')}.${type.split('/')[1].replace('jpeg', 'jpg')}`); window.setTimeout(() => URL.revokeObjectURL(url), 800) }
      setExporting(false); setShowExport(false); notify('Edited image downloaded', `${exportFormat} · ${exportQuality}`); return
    }
    const url = asset?.url ?? URL.createObjectURL(new Blob([JSON.stringify(projectData, null, 2)], { type: 'application/json' }))
    triggerDownload(url, asset ? `nova-export-${asset.name}` : 'nova-studio-project.nova.json')
    if (!asset) window.setTimeout(() => URL.revokeObjectURL(url), 1000)
    setExporting(false); setShowExport(false)
    notify('Download started', asset ? 'Your original media file has been downloaded. Web-only editing previews are applied in the canvas.' : 'Your editable Nova Studio project file is saved to your device.')
  }
  const downloadProjectBackup = () => {
    const data = JSON.stringify({ app: 'Nova Studio', version: 1, sourceMedia: asset?.name ?? null, filter, adjustments, savedAt: new Date().toISOString() }, null, 2)
    const url = URL.createObjectURL(new Blob([data], { type: 'application/json' })); const link = document.createElement('a')
    link.href = url; link.download = 'nova-studio-editable-project.json'; document.body.appendChild(link); link.click(); link.remove(); window.setTimeout(() => URL.revokeObjectURL(url), 500)
    notify('Project backup downloaded', 'Save this file to preserve your Nova Studio edit settings.')
  }
  const togglePlayback = () => { if (asset?.type === 'video' && videoRef.current) { if (playing) videoRef.current.pause(); else videoRef.current.play() }; setPlaying(!playing) }
  useEffect(() => { if (!toast) return; const id = window.setTimeout(() => setToast(null), 3200); return () => window.clearTimeout(id) }, [toast])
  const mediaStyle = { filter: `${filter === 'Cinematic' ? 'contrast(1.15) saturate(1.2) brightness(.94)' : filter === 'Portrait' ? 'brightness(1.08) saturate(.87) sepia(.08)' : filter === 'Noir' ? 'grayscale(1) contrast(1.3)' : filter === 'Velvet' ? 'hue-rotate(320deg) saturate(1.15)' : ''} brightness(${.55 + adjustments.exposure / 120}) contrast(${.55 + adjustments.contrast / 100}) saturate(${adjustments.saturation / 50})` }
  return <main className="studio-shell">
    <header className="topbar"><div className="brand"><div className="brand-mark"><Sparkles size={15}/></div><span>NOVA</span><b>WORKSPACE</b></div><div className="project-switcher"><span className="project-dot"/> Campaign 2025 <ChevronDown size={14}/></div><nav><button className="nav-active">Editor</button><button onClick={() => setHub('projects')}>Projects</button><button onClick={() => setHub('library')}>Library</button><button onClick={() => setShowAi(true)}>AI</button>{fireflyMode && <span className="firefly-pill"><Zap size={12}/> Premium AI</span>}</nav><div className="top-actions"><button className="phone-download" onClick={() => setShowInstall(true)}><Smartphone size={15}/> Mobile</button><button className="icon-button" onClick={() => notify('Search', 'Search is ready for your next project.')}><Search size={17}/></button><button className="icon-button" onClick={() => notify('Cloud sync complete', 'All project changes are saved.')}><Cloud size={17}/></button><span className="divider"/><button className="avatar">JM</button><button className="share" onClick={() => setShowExport(true)}><Download size={16}/> Export</button></div></header>
    <section className="workspace"><aside className="rail">{tools.map(({ icon: Icon, label }) => <button key={label} onClick={() => { setActiveTool(label); if (label === 'AI tools') setShowAi(true) }} className={`rail-tool ${activeTool === label ? 'chosen' : ''}`}><Icon size={19}/><span>{label}</span></button>)}<div className="rail-bottom"><button className="rail-tool" onClick={() => notify('Settings', 'Workspace preferences are up to date.')}><Settings2 size={19}/><span>Settings</span></button></div></aside>
      <section className="left-panel"><div className="panel-heading"><div><span className="eyebrow">WORKSPACE</span><h2>Untitled project</h2></div><button className="more">•••</button></div><div className="mode-switch"><button onClick={() => setMode('Photo')} className={mode === 'Photo' ? 'on' : ''}><ImageIcon size={15}/> Photo</button><button onClick={() => setMode('Video')} className={mode === 'Video' ? 'on' : ''}><Video size={15}/> Video</button></div><button className="import-button" onClick={() => inputRef.current?.click()}><Upload size={16}/> Import media <span>⌘ I</span></button><input ref={inputRef} type="file" accept="image/*,video/*" hidden onChange={e => upload(e.target.files)}/><div className="recent-chips"><button onClick={() => setShowAi(true)}><Sparkles size={13}/> Generate</button><button onClick={() => action('Smart resize')}><Frame size={13}/> Resize</button></div><div className="asset-label"><span>YOUR MEDIA</span><button onClick={() => inputRef.current?.click()}><Plus size={16}/></button></div>{asset ? <div className="asset-card"><div className="thumb">{asset.type === 'image' ? <img src={asset.url} alt="Imported media"/> : <Film size={24}/>}</div><div><b>{asset.name}</b><small>{asset.type === 'video' ? 'Video clip · 4K ready' : 'Photo asset · High resolution'}</small></div><button onClick={() => setAsset(null)} aria-label="Remove asset"><X size={14}/></button></div> : <div className="empty-assets"><Library size={25}/><b>Your canvas is ready</b><p>Import a photo or video to begin creating.</p></div>}<div className="projects-label"><span>PROJECT FILES</span><ChevronDown size={14}/></div><div className="project-file"><FolderOpen size={16}/><span>Campaign 2025</span></div><div className="storage-card"><Cloud size={15}/><span><b>Creative Cloud</b><small>4.8 GB of 20 GB used</small></span><i><em/></i></div></section>
      <section className="editor"><div className="editor-bar"><div className="crumb"><span>Campaign 2025</span><i>/</i><b>Hero Visual</b><em><Check size={11}/> Synced</em></div><div className="canvas-actions"><button onClick={() => { setFilter('Original'); setAdjustments({ exposure: 54, contrast: 58, saturation: 54 }); notify('Edits reset', 'Restored your original visual settings.') }}><RotateCcw size={15}/></button><button onClick={() => setZoom(Math.max(30, zoom - 10))}><ZoomOut size={15}/></button><span>{zoom}%</span><button onClick={() => setZoom(Math.min(140, zoom + 10))}><ZoomIn size={15}/></button></div></div><div className="canvas-wrap">{asset ? <div className="artboard uploaded" style={{ transform: `scale(${zoom / 100})` }}>{asset.type === 'image' ? <img src={asset.url} alt="Canvas content" className="canvas-media" style={mediaStyle}/> : <video ref={videoRef} src={asset.url} className="canvas-media" style={mediaStyle} onEnded={() => setPlaying(false)} controls/>}{autoEditing && <div className="ai-processing"><Sparkles size={24}/><b>Nova AI is perfecting your edit</b><span>Analyzing scene, subjects, color and motion</span><i/></div>}</div> : <div className="artboard placeholder" style={{ transform: `scale(${zoom / 100})` }}><div className="placeholder-content"><div className="glow-orb orb-one"/><div className="glow-orb orb-two"/><div className="new-scene"><Sparkles size={26}/><h1>Create without limits</h1><p>One intelligent space for photo, video, design, and every idea in between.</p><div><button onClick={() => inputRef.current?.click()}><Plus size={17}/> Add media</button><button className="ghost-start" onClick={() => setShowAi(true)}><Wand2 size={16}/> Explore AI</button></div></div><div className="editor-stamp">NOVA STUDIO <span>•</span> CREATIVE CLOUD</div></div></div>}</div><div className="timeline"><div className="timeline-top"><div><Clapperboard size={15}/><b>{mode} timeline</b></div><div><button onClick={togglePlayback}>{playing ? <Pause size={13}/> : <Play size={13}/>} {playing ? 'Pause' : 'Preview'}</button><button onClick={() => notify('Scene added', 'A new scene is ready in your timeline.')}><Plus size={15}/> Add scene</button></div></div><div className="ruler"><span>00:00</span><span>00:05</span><span>00:10</span><span>00:15</span><span>00:20</span></div><div className="track"><span className="track-name">Scene 01</span><div className={`clip ${playing ? 'is-playing' : ''}`}><div className="clip-preview"/><b>{asset?.name || 'Hero visual — Untitled project'}</b><span>00:12</span></div></div></div></section>
      <aside className="inspector"><div className="inspector-tabs"><button className="active">Edit</button><button onClick={() => notify('Animation controls', 'Smart motion presets are available for your scene.')}>Animate</button></div><section className="inspect-section"><div className="inspect-title"><b>Intelligence</b><span className="ai-ready"><i/> Ready</span></div><button className="ai-action" onClick={runAutoEdit}><span><Sparkles size={16}/> Auto edit with Nova AI</span><ChevronDown size={15}/></button><p className="ai-caption">One click to professionally enhance your full scene.</p><div className="quick-grid"><button onClick={() => action('Background removal')}><Eraser size={17}/>Remove<br/>background</button><button onClick={() => action('Portrait retouch')}><Aperture size={17}/>Retouch<br/>portrait</button><button onClick={() => action('Smart resize')}><MonitorPlay size={17}/>Smart<br/>resize</button></div></section><section className="inspect-section"><div className="inspect-title"><b>Looks</b><button onClick={() => setFilter('Original')}>Reset</button></div><div className="looks">{filterOptions.map(f => <button key={f} onClick={() => setFilter(f)} className={filter === f ? 'look-selected' : ''}><i className={`look-image look-${f.toLowerCase()}`}/><span>{f}</span></button>)}</div></section><section className="inspect-section adjust"><div className="inspect-title"><b>Adjust</b><SlidersHorizontal size={15}/></div>{(['exposure', 'contrast', 'saturation'] as const).map((key) => <label key={key}><span>{key[0].toUpperCase() + key.slice(1)}</span><output>{adjustments[key] - 50 > 0 ? '+' : ''}{adjustments[key] - 50}</output><input type="range" value={adjustments[key]} onChange={e => setAdjustments({ ...adjustments, [key]: Number(e.target.value) })}/></label>)}</section><section className="inspect-section"><div className="inspect-title"><b>Pro tools</b><Tune size={14}/></div><div className="pro-tools"><button onClick={() => action('Precision crop')}><Crop size={15}/><span><b>Crop & straighten</b><small>Composition controls</small></span></button><button onClick={() => action('Auto reframe')}><ScanLine size={15}/><span><b>Auto reframe</b><small>Keep subjects in focus</small></span></button></div></section></aside></section>
    {showAi && <div className="modal-backdrop" onClick={() => setShowAi(false)}><div className="ai-modal" onClick={e => e.stopPropagation()}><button className="close-modal" onClick={() => setShowAi(false)}><X size={17}/></button><div className="ai-modal-head"><div className="export-icon"><Sparkles size={22}/></div><div><span className="eyebrow">NOVA INTELLIGENCE</span><h2>What should we perfect?</h2></div></div><p>Professional-grade AI edits, built into your creative flow.</p><button className="firefly-connect" onClick={enableFirefly}><Zap size={18}/><span><b>Adobe Firefly Premium</b><small>Generative fill, expand & text effects</small></span><ChevronDown size={15}/></button><div className="ai-options">{aiTools.map(({ icon: Icon, name, copy }) => <button key={name} onClick={() => name === 'Auto edit' ? runAutoEdit() : action(name)}><Icon size={18}/><span><b>{name}</b><small>{copy}</small></span><ChevronDown size={15}/></button>)}</div><button className="auto-all" onClick={runAutoEdit}><Sparkles size={16}/> Auto-edit entire project</button></div></div>}
    {hub && <div className="modal-backdrop hub-backdrop" onClick={() => setHub(null)}><section className="hub-modal" onClick={e => e.stopPropagation()}><header><div><span className="eyebrow">NOVA CREATIVE SUITE</span><h2>{hub === 'projects' ? 'Your projects' : 'Creative library'}</h2></div><button className="close-modal" onClick={() => setHub(null)}><X size={17}/></button></header>{hub === 'projects' ? <><div className="hub-toolbar"><button className="import-button" onClick={() => { setHub(null); inputRef.current?.click() }}><Plus size={16}/> New project</button><span>Recently opened</span></div><div className="project-grid"><button className="project-tile active-project" onClick={() => setHub(null)}><i/><b>Campaign 2025</b><small>Edited just now · 1 scene</small></button><button className="project-tile" onClick={() => notify('New project', 'Start by importing a photo or video.')}><i/><b>New creative</b><small>Create from a blank canvas</small></button></div></> : <><p className="hub-copy">Your shared fonts, colors, visual styles, and reusable creative elements.</p><div className="suite-grid">{suiteTools.map(({ icon: Icon, title, copy }) => <button key={title} onClick={() => notify(title, `${copy} is ready in the editor.`)}><Icon size={20}/><b>{title}</b><small>{copy}</small><ChevronDown size={15}/></button>)}</div></>}<footer><BadgeCheck size={15}/> Your Creative Suite content is synced and ready.</footer></section></div>}
    {showInstall && <div className="modal-backdrop" onClick={() => setShowInstall(false)}><div className="install-modal" onClick={e => e.stopPropagation()}><button className="close-modal" onClick={() => setShowInstall(false)}><X size={17}/></button><div className="export-icon"><Smartphone size={22}/></div><h2>Nova Studio for mobile</h2><p>Scan this working QR code to open Nova Studio’s phone install page. Add it to your home screen for an app-like experience.</p><div className="qr" aria-label="Scannable QR code for Nova Studio mobile installation"><img src={`https://api.qrserver.com/v1/create-qr-code/?size=160x160&data=${encodeURIComponent(mobileInstallUrl)}`} alt="Scan to open Nova Studio on mobile"/></div><a className="android-link" href={mobileInstallUrl}><Download size={17}/> Install web app on phone</a><a className="apk-guide" href="/nova-studio-apk-build-guide.txt" download><Download size={15}/> Download Android APK build guide</a><small>An APK cannot be safely generated from a browser-only website. The included guide gives the exact native packaging path; a signed APK requires an Android signing key and app-owner account.</small></div></div>}
    {showExport && <div className="modal-backdrop" onClick={() => !exporting && setShowExport(false)}><div className="export-modal" onClick={e => e.stopPropagation()}><button className="close-modal" disabled={exporting} onClick={() => setShowExport(false)}><X size={17}/></button><div className="export-icon"><Download size={22}/></div><h2>{exporting ? 'Preparing download' : 'Export & download'}</h2><p>{asset?.type === 'image' ? 'Your selected image format is rendered with the current canvas color treatment.' : asset ? 'Video downloads preserve the original media. Server rendering is required to encode a new MP4.' : 'Save an editable project file to your device.'}</p><label>Format<select value={exportFormat} disabled={exporting} onChange={e => setExportFormat(e.target.value)}><option>PNG · High resolution</option><option>JPG · Web optimized</option><option>WebP · Modern web</option><option>MP4 · 4K · H.264</option><option>MP4 · 1080p · Web delivery</option><option>MOV · ProRes source</option></select></label><label>Quality<select value={exportQuality} disabled={exporting} onChange={e => setExportQuality(e.target.value)}><option>Maximum · 98%</option><option>High · 90%</option><option>Balanced · 75%</option></select></label><button className="export-now" disabled={exporting} onClick={() => void exportProject()}>{asset ? 'Render & download' : 'Download project'} <Download size={16}/></button>{asset && <button className="backup-export" onClick={downloadProjectBackup}>Download edit settings backup</button>}<small className="export-note">PNG, JPG and WebP render directly for imported photos. New MP4/MOV encoding needs a render backend.</small></div></div>}
    {toast && <div className="toast"><div><Check size={16}/></div><span><b>{toast.title}</b><small>{toast.text}</small></span><button onClick={() => setToast(null)}><X size={15}/></button></div>}
  </main>
}
export default App